# Dataset Generation Pipeline
version: '3.8'

services:
  dataset-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dataset-generator
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    volumes:
      - ./output:/app/output
      - ./config.yaml:/app/config.yaml:ro
    restart: "no"  # Run once and stop 