apiVersion: batch/v1
kind: Job
metadata:
  name: dataset-generation-job
  labels:
    app: dataset-generator
spec:
  template:
    spec:
      containers:
      - name: dataset-generator
        image: dataset-generator:latest
        command: ["python", "src/data/dataset_generator.py"]
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: output-volume
          mountPath: /app/output
      volumes:
      - name: output-volume
        emptyDir: {}
      restartPolicy: Never

